fix: update crossbeam-channel dependency (#2106)
## Summary
Fixes for a new `cargo audit` warning.

We get a warning when running `cargo audit` for
[RUSTSEC-2025-0024](https://rustsec.org/advisories/RUSTSEC-2025-0024).
This is for `crossbeam-channel@0.5.14`.

<details><summary>cargo audit output</summary><p>

```
Crate:     crossbeam-channel
Version:   0.5.14
Title:     crossbeam-channel: double free on Drop
Date:      2025-04-08
ID:        RUSTSEC-2025-0024
URL:       https://rustsec.org/advisories/RUSTSEC-2025-0024
Solution:  Upgrade to >=0.5.15
Dependency tree:
crossbeam-channel 0.5.14
└── moka 0.12.10
    └── astria-conductor 1.1.0

Crate:     crossbeam-channel
Version:   0.5.14
Warning:   yanked

error: 1 vulnerability found!
warning: 1 allowed warning found
```

</p></details>

## Changes
- Ran `cargo update -p crossbeam-channel`.

## Testing
Ran `cargo audit` locally.

## Changelogs
Conductor changelog updated.