fix(ci): use gh token to avoid rate limit for setup-protoc (#546)
## Summary
Avoid API rate limiting when installing protoc in CI by using a github
token

## Background
Our rust tests failed because protoc could not be installed, showing
this error:
Error: Error: API rate limit exceeded for 148.251.176.45. (But here's
the good news: Authenticated requests get a higher rate limit. Check out
the documentation for more details.)

## Changes
- Set the `repo-token` to `GITHUB_TOKEN` option in
`arduino/setup-protoc` steps to avoid API rate limits.

Co-authored-by: Jordan Oroshiba <jordan@astria.org>