chore: bump msrv and run clippy (#1167)
## Summary
latest rust is now 1.79 and also our code was using items supported in
rust 1.76 and the ci is using 1.76.0, so the msrv should be bumped:
```
error: current MSRV (Minimum Supported Rust Version) is `1.73.0` but this item is stable since `1.76.0`
   --> crates/astria-conductor/src/celestia/convert.rs:151:10
    |
151 |           .inspect_err(|err| {
    |  __________^
152 | |             info!(
153 | |                 error = err as &StdError,
154 | |                 target = SubmittedMetadataList::full_name(),
155 | |                 "failed decoding blob bytes; dropping the blob",
156 | |             );
157 | |         })
    | |__________^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#incompatible_msrv
```

also ran clippy and fixed the various lint issues.